#!/usr/bin/env bash

set -e

. "./utils/log.sh"
. "./utils/pacman.sh"
. "./utils/append.sh"
. "./utils/git.sh"

install fzf

log "Select modules:\n"
modules=$(find ./modules -type f | fzf --multi --height 20 --layout=reverse)
log "Selected modules:\n"
for module in $modules; do
  log "  $module\n"
done

modules_done=()

for module in $modules; do
  . "$module"
  modules_done+=("$module")
done

log "Executed modules:\n"
for module in "${modules_done[@]}"; do
  log "  %s\n" "$module"
done
