#!/usr/bin/env bash

set -e

. "./utils/log.sh"
. "./utils/pacman.sh"
. "./utils/append.sh"
. "./utils/git.sh"

install fzf

info "Select modules:\n"
modules=$(find ./modules -type f | fzf --multi --height 20 --layout=reverse)
info "Selected modules:\n"
for module in $modules; do
  info "  $module\n"
done

modules_done=()

for module in $modules; do
  . "$module"
  modules_done+=("$module")
done

info "Executed modules:\n"
for module in "${modules_done[@]}"; do
  info "  %s\n" "$module"
done
