#!/usr/bin/env bash

set -e

. "./utils/log.sh"
. "./utils/pacman.sh"
. "./utils/append.sh"
. "./utils/git.sh"

install fzf

info "Select modules:\n"
modules=$(find ./modules -type f | fzf --multi --height 20 --layout=reverse)
info "Selected modules:\n"
for module in $modules; do
  info "  $module\n"
done

modules_done=()

for module in $modules; do
  . "$module"
  modules_done+=("$module")
done

info "Executed modules:\n"
for module in "${modules_done[@]}"; do
  info "  %s\n" "$module"
done

## Go development
#sudo pacman -S --noconfirm go
#sudo pacman -S --noconfirm gopls
#sudo pacman -S --noconfirm delve
#cat >> $HOME/.bashrc <<'EOF'
## Go
#export GOPATH=$HOME/.go
#export PATH=$GOPATH/bin:$PATH
#EOF
#
## Lua development
#sudo pacman -S --noconfirm lua-language-server
#
## Web developement
#sudo pacman -S --noconfirm wget
#sudo pacman -S --noconfirm curl
#sudo pacman -S --noconfirm vscode-css-languageserver
#sudo pacman -S --noconfirm typescript-language-server
