#!/usr/bin/env bash

log "Setting KDE look and feel...\n"
plasma-apply-lookandfeel -a org.kde.breezedark.desktop

log "Setting KDE fixed font...\n"
install ttf-iosevka-nerd
kwriteconfig5 --group General --key fixed "Iosevka Nerd Font,12,-1,5,50,0,0,0,0,0"

log "Disable cursor launch feedback...\n"
kwriteconfig5 --file klaunchrc --group BusyCursorSettings --key Bouncing --type bool "false"
kwriteconfig5 --file klaunchrc --group FeedbackStyle --key BusyCursor --type bool "false"

log "Setting SDDM theme...\n"
sudo_append "/etc/sddm.conf.d/kde_settingsconf" '[Theme]
Current=breeze
CursorTheme=breeze_cursors
Font=Noto Sans,10,-1,0,50,0,0,0,0,0'

