#!/usr/bin/env bash

log "Setting KDE look and feel...\n"
plasma-apply-lookandfeel -a org.kde.breezedark.desktop

log "Setting double click behaviour...\n"
kwriteconfig5 --group KDE --key SingleClick --type bool "false"

log "Setting KDE fixed font...\n"
install ttf-iosevka-nerd
kwriteconfig5 --group General --key fixed "Iosevka Nerd Font,12,-1,5,50,0,0,0,0,0"

log "Disable cursor launch feedback...\n"
kwriteconfig5 --file klaunchrc --group BusyCursorSettings --key Bouncing --type bool "false"
kwriteconfig5 --file klaunchrc --group FeedbackStyle --key BusyCursor --type bool "false"

log "Disable keep clipboard across desktop sessions...\n"
kwriteconfig5 --file klipperrc --group General --key KeepClipboardContents --type bool "false"

log "Always start with empty session...\n"
kwriteconfig5 --file ksmserverrc --group General --key loginMode "emptySession"

log "Configuring alt-tab behaviour...\n"
kwriteconfig5 --file kwinrc --group TabBox --key LayoutName "thumbnail_grid"

log "Setting SDDM theme...\n"
sudo_append "/etc/sddm.conf.d/kde_settings.conf" '[Theme]
Current=breeze
CursorTheme=breeze_cursors
Font=Noto Sans,10,-1,0,50,0,0,0,0,0'

log "Configuring plymouth for KDE...\n"
install plymouth-kcm
install breeze-plymouth
sudo plymouth-set-default-theme -R breeze

log "Disable KDE splash screen...\n"
kwriteconfig5 --file ksplashrc --group KSplash --key Engine "none"
kwriteconfig5 --file ksplashrc --group KSplash --key Theme "None"

log "Installing additional KDE apps...\n"
install gwenview
