#!/usr/bin/env bash

install plymouth

log "Setting up silent boot...\n"
loader_entry="$(ls /boot/loader/entries/*_linux.conf)"
log "Found loader entry '$loader_entry'\n"
options="$(grep -P "^options\s+.*$" "$loader_entry")"
log "Found '$options'\n"
options_to_add="splash quiet loglevel=3 systemd.show_status=auto rd.udev.log_level=3"

for option in $options_to_add; do
  if echo -n "$options" | grep -F -q "$option"; then
    log "'$option' does already exist\n"
  else
    log "Adding option '$option'...\n"
    options="$options $option"
  fi
done

log "Writing '$options' to '$loader_entry'...\n"
options_escaped="$(echo -n "$options" | sed -e 's/[]\/$*.^[]/\\&/g')"
log "Escaped string: '$options_escaped'\n"
sudo sed "s/^options.*$/$options_escaped/" -i "$loader_entry" 


mkinitcpio_conf="/etc/mkinitcpio.conf"
log "Reading '$mkinitcpio_conf'...\n"
hooks="$(grep -F "HOOKS=(" $mkinitcpio_conf)"
log "$hooks\n"
if echo -n "$hooks" | grep -q "plymouth"; then
  log "'plymouth' hook does already exist\n"
else
  if echo -n "$hooks" | grep -q "encrypt"; then
    log "'encrypt' hook exists\n"
    log "Adding 'plymouth' hook before 'encrypt'...\n"
    hooks="$(echo -n "$hooks" | sed 's/encrypt/plymouth encrypt/')"
  else
    log "Appending 'plymouth' hook...\n"
    hooks="$(echo -n "$hooks" | sed 's/)/ plymouth)/')"
  fi
  log "Writing '$hooks' to '$mkinitcpio_conf'...\n"
  hooks_escaped="$(echo -n "$hooks" | sed -e 's/[]\/$*.^[]/\\&/g')"
  log "Escaped string: '$hooks_escaped'\n"
  sudo sed "s/^HOOKS=(.*$/$hooks_escaped/" -i "$mkinitcpio_conf" 
  sudo mkinitcpio -p linux
fi
