#!/usr/bin/env bash

install jq
install bitwarden-cli

function lock() {
  bw lock
}

trap lock EXIT

set +e
while [ "$(bw status | jq -r .status)" == "unauthenticated" ]; do
  log "Bitwarden login\n"
  bw login
done
set -e

log "Bitwarden login successful\n"

set +e
while [ -z "$BW_SESSION" ]; do
  log "Unlocking Bitwarden...\n"
  session="$(bw unlock --raw)"
  export BW_SESSION="$session"
done
set -e
