#!/usr/bin/env bash

function append() {
  file="$1"
  if ! [ -f "$file" ]; then
    log "File '$file' does not exist\n"
    log "Creating file '$file'...\n"
    mkdir -p "$(dirname "$file")"
    touch "$file"
  fi
  content="$2"
  pattern="$(echo -n "$content" | tr '\n' ' ')"
  if cat "$file" | tr '\n' ' ' | grep -F -q "$pattern"; then
    log "'$file' already contains '$content'\n"
  else
    log "Writing to '$file'...\n"
    if [ -s "$file" ]; then
      log "'$file' is not empty\n"
      log "Adding newline to '$file'\n"
      echo >> "$file"
    fi
    echo -n "$content" | tee -a "$file" > /dev/null
    log "Written to '$file': '$content'\n"
  fi
}

function sudo_append() {
  file="$1"
  if ! [ -f "$file" ]; then
    log "File '$file' does not exist\n"
    log "Creating file '$file'...\n"
    sudo mkdir -p "$(dirname "$file")"
    sudo touch "$file"
  fi
  content="$2"
  pattern="$(echo -n "$content" | tr '\n' ' ')"
  if sudo cat "$file" | tr '\n' ' ' | grep -F -q "$pattern"; then
    log "'$file' already contains '$content'\n"
  else
    log "Writing to '$file'...\n"
    if [ -s "$file" ]; then
      log "'$file' is not empty\n"
      log "Adding newline to '$file'\n"
      echo | sudo tee -a "$file"
    fi
    echo -n "$content" | sudo tee -a "$file" > /dev/null
    log "Written to '$file': '$content'\n"
  fi
}
